# Generated by Django 3.0.7 on 2020-07-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200704_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='sale_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='цена продажи'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='цена ремонта'),
        ),
    ]
